configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hubmap-consortium-hubmap-m1%2Fhubmap-search-sdk-d152b0f4a7d7aa376be622312bc396cb4c9dc5dd0af6cd3bd86c2839d970639c.yml
